#!/bin/bash

# Verifica se um diretório foi fornecido como argumento
if [ $# -eq 0 ]; then
  echo "Uso: $0 <diretorio>"
  exit 1
fi

# Diretório de entrada
diretorio="$1"

# Loop para percorrer todos os arquivos e subdiretórios
find "$diretorio" -type f -name "*.ANS" -print0 | while IFS= read -r -d $'\0' arquivo; do
  iconv -f 437 "$arquivo"
done
